---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    tier: database
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "appdb"
  PGDATA: "/var/lib/postgresql/data/pgdata"