---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    tier: database
type: Opaque
data:
  # Base64 encoded value of "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM=