apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  namespace: somkiatworkshop
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Users/somkiatpuisungnoen/data/slide/k8s/demo-nodejs-postgres/k8s/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: somkiatworkshop
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual